apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: velero-backup
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
      spec:
      containers:
      - name: velero
      image: velero/velero:v1.7.0
      command:
      - /velero
      args:
      - backup
      - create
      - my-backup
      volumeMounts:
      - name: cloud-credentials
      mountPath: /credentials
      env:
      - name: AWS_ACCESS_KEY_ID
      valueFrom:
      secretKeyRef:
      name: cloud-credentials
      key: aws_access_key_id
      - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
      secretKeyRef:
      name: cloud-credentials
      key: aws_secret_access_key
      volumes:
      - name: cloud-credentials
      secret:
      secretName: cloud-credentials