apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        forward . 185.225.168.168 # you can use resove.conf file /etc/resolv.conf
        prometheus :9153
        cache 30
        loop
        reload
        loadbalance
    }


# kubectl get -n kube-system cm/coredns --export -o yaml 
# kubectl replace -n kube-system -f coredns_cm.yaml 
